"use strict";
const pnome = 'senai AL';
let sobreNome = 'Benedito Bentes';
let numerocasa = 1045;
let total = 57085.32;
let soma = numerocasa + total;
console.log(typeof soma);
console.log(pnome);
console.log(sobreNome);
console.log(numerocasa);
console.log(typeof numerocasa);
console.log(typeof total);
